{% set name = "femtoscope" %}
{% set version = "0.2.3" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/femtoscope-{{ version }}.tar.gz
  sha256: eca4b45df2d5a5d92423d471d9b4437847a74e43efce471cb56f51045a96002a

build:
  noarch: python
  entry_points:
    - generate-femtoscope-docs = femtoscope.misc.generate_documentation:main
    - run-femtoscope-tests = femtoscope.tests.run_tests:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - python-gmsh ==4.11.1
    - matplotlib-base
    - meshio ==4.4.6
    - numpy <2
    - pandas
    - pyevtk
    - pyvista
    - sfepy >=2024.3

test:
  imports:
    - femtoscope
  commands:
    - python -m femtoscope.tests.run_tests
  requires:
    - python {{ python_min }}
    - pytest

about:
  home: https://pypi.org/project/femtoscope/
  summary: Python code for solving nonlinear PDEs from modified gravity models on unbounded domains
  dev_url: https://github.com/onera/femtoscope
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - livoire13
